on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish to Netlify

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      DISPLAY: ':99.0'
      RGL_USE_NULL: true
      LANG: "en_US.UTF-8"
      TZ: "Asia/Shanghai"
      ## RETICULATE_PYTHON_ENV: "/opt/.virtualenvs/r-tensorflow"
      ## CMDSTAN_VERSION: "2.29.2"
      ## CMDSTAN: "/opt/cmdstan/cmdstan-2.29.2"
      ## CMDSTANR_NO_VER_CHECK: true
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '2.19.2'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: '4.2.2'
          extra-repositories: 'https://mc-stan.org/r-packages'  
        
      - name: Render and Publish 
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: netlify
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          
